### ISSUE TITLE
Add ProjectPackageVersions as subcommand

### ISSUE THREAD

**Issue by edoardottt** [edoardottt/depsdev#35]
See https://docs.deps.dev/api/v3alpha/#getprojectpackageversions.

The PR should add the subcommand (in the `cmd` folder), the API structs and the methods necessary to interact with the API. 

Ping me here if you need additional help :)

**Comment by shivankurchavan** [comment]
id like to work on this issue

**Comment by edoardottt** [comment]
Amazing! Let me know if you understand what you should do by looking at the codebase or you need a lil bit of guidance :)

**Comment by edoardottt** [comment]
everything okay? @shivankurchavan please let me know otherwise I'll have to assign to another dev

**Comment by shivankurchavan** [comment]
Hey, sorry about that. Actually I am not able to solve it. Please go ahead and assign it to someone else.

**Comment by edoardottt** [comment]
Understood, no worries :) thanks for the update!

**Comment by edoardottt** [comment]
done
