### ISSUE TITLE
Add a link to the package documentation in the README

### ISSUE THREAD

**Issue by edoardottt** [edoardottt/depsdev#39]
Add this

```
Read the full [`package documentation here`](https://pkg.go.dev/github.com/edoardottt/depsdev/pkg/depsdev)
```

under the example in subsection `Use depsdev as a Go module` in the README

**Comment by Ritish134** [comment]
Hi there excited to contribute. can you assign me :)

**Comment by Ritish134** [comment]
Created a pull Request #41

**Comment by edoardottt** [comment]
Completed, thanks @Ritish134 !
