### ISSUE TITLE
GetProject method sometime fails due to wrong type return by the depsdev API

### ISSUE THREAD

**Issue by zaibon** [edoardottt/depsdev#51]
**Describe the bug**
Some project detail in the depsdev database have the wrong type in the ossFuzz object.
Example: https://api.deps.dev/v3alpha/projects/github.com%2Fklauspost%2Fcompress

`lineCount` and `lineCoverCount` are strings while they should be integer. This prevents the unmarshaling of this project by this library.

**To Reproduce**
1. use the `GetProject` with argument `"github.com/klauspost/compress"`

**Expected behavior**
Get project details from the API

**Comment by edoardottt** [comment]
Hi @zaibon, what do you mean with `This prevents the unmarshaling of this project by this library`?

The command 
```console
depsdev project "github.com/klauspost/compress" | jq
```
works fine for me.

I agree those two fields must be changed to int64, but how can this produce errors?

**Comment by zaibon** [comment]
Try this code:
```golang
package main

import (
	"fmt"

	"github.com/edoardottt/depsdev/pkg/depsdev"
)

func main() {
	client := depsdev.NewAPI()
	i, err := client.GetProject("github.com/klauspost/compress")
	if err != nil {
		fmt.Println(err)
		return
	}

	fmt.Println(i)
}
```
Running this code returns: `json: cannot unmarshal string into Go struct field OssFuzz.ossFuzz.lineCount of type int64`

**Comment by edoardottt** [comment]
Thanks for let me know ! @zaibon 

Actually I'm not the maintainer of the deps.dev APIs since that it's a Google project. I'll open an issue and see what they reply to me.
