### ISSUE TITLE
Add support for Batch

### ISSUE THREAD

**Issue by edoardottt** [edoardottt/depsdev#67]
- https://docs.deps.dev/api/v3alpha/index.html#getversionbatch
- https://docs.deps.dev/api/v3alpha/index.html#getprojectbatch

**Comment by zaibon** [comment]
I've started to explore some possible implementation for the two batch methods.
You can have a look at https://github.com/zaibon/depsdev/tree/v3Alpha-batch to see if you would be interested in this kind of solution.

**Comment by edoardottt** [comment]
thanks @zaibon ! appreciated. waiting for a PR (remember to use `devel` branch) :)

I'm here for any question
